<?php

return [
    'identity' => [
        'name' => 'Badan Pusat Statistik (BPS) Kabupaten Batang Hari',
        'address' => 'Jl. Jenderal Sudirman, Rengas Condong, Muara Bulian, Kabupaten Batang Hari, Jambi 36613',
        'phone' => '(0743) 21008',
        'head_of_office' => 'Hartono',
        'operating_hours' => 'Senin - Kamis: 07.30 - 16.00 WIB, Jumat: 07.30 - 16.30 WIB',
        'website' => 'https://batangharikab.bps.go.id',
        'email' => 'bps1504@bps.go.id'
    ],
    'vision' => 'Lembaga yang Independen, Tepercaya, dan Berperan Aktif dalam Mendukung Perumusan Kebijakan Berbasis Data Bersama Indonesia Maju Menuju Indonesia Emas 2045.',
    'mission' => "1. Menyediakan data statistik berkualitas melalui kegiatan statistik yang terintegrasi dan berstandar internasional.\n2. Memperkuat peran sebagai pembina data statistik bagi instansi pemerintah dan masyarakat.\n3. Membangun Sistem Statistik Nasional yang andal, efektif, dan efisien.",
    'tasks' => "BPS bertugas menyediakan data bagi pemerintah dan masyarakat, membantu kegiatan statistik kementerian/lembaga, mengembangkan standar teknik statistik, dan membangun kerjasama internasional.",
    'services' => "Pelayanan Statistik Terpadu (PST) dapat diakses langsung di kantor atau melalui website. Layanan mencakup konsultasi data, rekomendasi kegiatan statistik, dan penjualan publikasi.",
    'kbli_info' => "KBLI (Klasifikasi Baku Lapangan Usaha Indonesia) adalah pengklasifikasian aktivitas ekonomi Indonesia yang menghasilkan produk/output, baik berupa barang maupun jasa, berdasarkan lapangan usaha.",
    'dynamic_tables' => "Fitur 'Tabel Dinamis' (Query Builder) di website BPS Batang Hari memungkinkan pengguna membuat tabel data custom. Langkah-langkahnya:
1. Pilih Data: Tentukan subjek, indikator/variabel, karakteristik, dan periode waktu yang diinginkan.
2. Pilih Tata Letak: Tentukan variabel untuk baris dan kolom.
3. Unduh: Klik Submit untuk melihat hasil, lalu unduh dalam format Excel, CSV, atau PDF.",
    'statistics_subjects' => [
        "Sosial dan Kependudukan" => [
            "Jumlah Penduduk",
            "Kepadatan Penduduk",
            "Rasio Jenis Kelamin",
            "Laju Pertumbuhan Penduduk",
            "Penduduk Lansia",
            "Angka Kelahiran (CBR)",
            "Angka Kematian (CDR)",
            "Migrasi Masuk",
            "Migrasi Keluar",
            "Indeks Pembangunan Manusia (IPM)",
            "Angka Harapan Hidup (AHH)",
            "Rata-rata Lama Sekolah (RLS)",
            "Harapan Lama Sekolah (HLS)",
            "Pengeluaran per Kapita",
            "Gini Ratio (Ketimpangan)",
            "Jumlah Penduduk Miskin",
            "Persentase Penduduk Miskin",
            "Garis Kemiskinan",
            "Indeks Kedalaman Kemiskinan",
            "Tingkat Pengangguran Terbuka (TPT)",
            "Tingkat Partisipasi Angkatan Kerja (TPAK)",
            "Penduduk Bekerja",
            "Pencari Kerja Terdaftar",
            "Upah Minimum Kabupaten (UMK)",
            "Status Pekerjaan Utama"
        ],
        "Pendidikan dan Kesehatan" => [
            "Angka Melek Huruf",
            "Angka Partisipasi Sekolah (APS)",
            "Angka Partisipasi Kasar (APK)",
            "Angka Partisipasi Murni (APM)",
            "Angka Putus Sekolah",
            "Rasio Murid-Guru",
            "Jumlah SD/MI",
            "Jumlah SMP/MTs",
            "Jumlah SMA/SMK/MA",
            "Jumlah Perguruan Tinggi",
            "Jumlah Rumah Sakit",
            "Jumlah Puskesmas",
            "Jumlah Posyandu",
            "Tenaga Medis (Dokter/Perawat)",
            "Angka Kematian Bayi (IMR)",
            "Angka Kematian Ibu (MMR)",
            "Prevalensi Gizi Buruk (Stunting)",
            "Cakupan Imunisasi Dasar",
            "Persentase Balita Gizi Buruk",
            "Sanitasi Layak"
        ],
        "Ekonomi dan Perdagangan" => [
            "PDRB Atas Dasar Harga Berlaku (ADHB)",
            "PDRB Atas Dasar Harga Konstan (ADHK)",
            "Laju Pertumbuhan PDRB",
            "PDRB Per Kapita",
            "Struktur Ekonomi Daerah",
            "Inflasi Bulanan (mtm)",
            "Inflasi Tahunan (yoy)",
            "Indeks Harga Konsumen (IHK)",
            "Indeks Harga Perdagangan Besar (IHPB)",
            "Nilai Tukar Petani (NTP)",
            "Nilai Tukar Usaha Pertanian (NTUP)",
            "Ekspor Netto",
            "Impor Netto",
            "Investasi (PMDN/PMA)",
            "Realisasi Penerimaan Daerah",
            "Belanja Daerah",
            "Dana Desa",
            "Koperasi Aktif",
            "UMKM Binaan"
        ],
        "Pertanian dan Pertambangan" => [
            "Luas Panen Padi",
            "Produksi Padi (GKG)",
            "Produktivitas Padi",
            "Luas Panen Jagung",
            "Produksi Jagung",
            "Luas Panen Kedelai",
            "Produksi Kedelai",
            "Produksi Kelapa Sawit",
            "Produksi Karet",
            "Produksi Kelapa",
            "Produksi Kakao",
            "Produksi Kopi",
            "Populasi Sapi Potong",
            "Populasi Kambing/Domba",
            "Populasi Ayam Ras",
            "Produksi Daging Ternak",
            "Produksi Telur",
            "Produksi Susu Segar",
            "Produksi Perikanan Tangkap",
            "Produksi Perikanan Budidaya",
            "Produksi Batubara",
            "Produksi Minyak Bumi",
            "Produksi Gas Alam"
        ],
        "Infrastruktur, Pariwisata, dan Lainnya" => [
            "Panjang Jalan (Km)",
            "Kondisi Jalan (Baik/Rusak)",
            "Jembatan",
            "Jumlah Kendaraan Bermotor",
            "Jumlah Penumpang Angkutan Umum",
            "Jumlah Wisatawan Nusantara",
            "Jumlah Wisatawan Mancanegara",
            "Tingkat Penghunian Kamar (TPK) Hotel",
            "Rata-rata Lama Menginap",
            "Jumlah Hotel/Akomodasi",
            "Restoran/Rumah Makan",
            "Luas Wilayah",
            "Curah Hujan",
            "Hari Hujan",
            "Bencana Alam",
            "Desa/Kelurahan",
            "Kecamatan",
            "Jumlah Pegawai Negeri Sipil (PNS)",
            "Anggota DPRD"
        ]
    ]
];
